version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: reismatheus97/reverseproxy
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: reismatheus97/backend-user
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed
    image: reismatheus97/backend-feed
  frontend:
    build:
      context: ../../udacity-c3-frontend
    image: reismatheus97/udacity-frontend:local
